### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by Mayelna** [sendinblue/APIv3-php-library#213]
Hello.  I installed the API tool via composer then copied the example from the main page and edited it to add my API key info.  I wasn't sure what the "partner key" was about, so I remarked that out.  I then saved and ran it and got:

_Exception when calling AccountApi->getAccount: [0] cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.sendinblue.com/v3/account_

What is the problem there?  Was remarking out the partner thing a problem?  If so, where do I get my "partner key"?  Thanks!

**Comment by preetishishodia7** [comment]
Hi @Mayelna  remaking out "partner-key" isn't it a problem. I run the same example by without partner-key it's working fine at our end. There is some issue at your end. Also  can you please tell which version of PHP are you using. We suggest not to use higher version than PHP 7.4. It can also be the issue , because we are not supporting >7.4 PHP version currently.
