### ISSUE TITLE
No way to find: folder with its name, sender by his mail or id...

### ISSUE THREAD

**Issue by EVDW** [sendinblue/APIv3-php-library#22]
I think it's too bad to not be able to recover a folder by its name, because each time I add a contact list, I have to create a new folder and I can't reuse one because I don't know its id.
Do you think it will be a possible feature to add to the API?

**Comment by EVDW** [comment]
And I have the same issue with senders... I can't recover a sender by his email?

**Comment by EVDW** [comment]
Sorry to post again but... When we create a Sender, its id isn't return, so I can't loop on all Senders and find the one I want by its id.

**Comment by EVDW** [comment]
So, I really tried to use this librairy, but too much problems to recover informations. I'm giving up.

**Comment by ekta-slit** [comment]
Hi @EVDW 

Regarding your queries:

> I think it's too bad to not be able to recover a folder by its name

You can get folder by using its `id` only ( unique between folders ) because a folder with same name can be created multiple times, so getting folder details by its name doesn't makes any worth.


> Sorry to post again but... When we create a Sender, its id isn't return, so I can't loop on all Senders and find the one I want by its id after that.

When a sender is created response is below with `201` http status code:
```
{
    "id": 1
}
```
you can definitely use this `id` to loop on all Senders.

Hope that helps!

Thanks
