### ISSUE TITLE
GetEmailCampaigns & new parameter

### ISSUE THREAD

**Issue by Pascal76** [sendinblue/APIv3-php-library#255]
For GetEmailCampaigns, from the doc : "You now need to specify which type of statistics you would like to retrieve."
How to add this parameter to the function ?
$apiInstance->getEmailCampaigns($type, $status, $startDate, $endDate, $limit, $offset, $statistics);
does not work.

**Comment by KoriaLL** [comment]
"Hello Pascal76,

I have exactly the same issue with this API. I have been using it for several years, but for about a month now, I can't retrieve statistics with the PHP SDK anymore... The reason is very simple, they changed the API's functionality 28 days ago, without updating the SDK accordingly...

https://developers.sendinblue.com/changelog/get-all-marketing-campaigns

The last SDK update was on January 6, 2023, while the API has changed in February (see images).

![image](https://user-images.githubusercontent.com/22171394/223439264-c36ad936-3c27-4425-a1c2-cced974204d9.png)
![image](https://user-images.githubusercontent.com/22171394/223439553-d8f110fb-2bdf-405a-85d0-9125234ace5b.png)

So, apart from manually making the calls without the SDK, there aren't too many solutions in my opiginon...

I've had a support ticket on this issue with them for several weeks now, and it's far from being very responsive..."

**Comment by Pascal76** [comment]
Hello @KoriaLL 
I just contacted the head of deliverability.
I hope he can help us.

**Comment by preetishishodia7** [comment]
HI @Pascal76 @KoriaLL 

This functionality will be added soon, we are on it [ref](https://github.com/sendinblue/APIv3-php-library/pull/258).
Thanks!

**Comment by preetishishodia7** [comment]
Hi @Pascal76 @KoriaLL 
We have fixed this issue in our latest SDK update i.e. 8.4.2 please use that. For now we are closing this issue.
Feel free to add if you face any issue.
Thanks!
