### ISSUE TITLE
install library with composer

### ISSUE THREAD

**Issue by thamerbelfkihthamer** [sendinblue/APIv3-php-library#35]
i have just run added the         "sendinblue/api-v3-sdk": "*@dev" inside my composer.json file to install this package and i runned composer install but the package don't download.

i runned it for both  laravel and symfony project

**Comment by mirsch** [comment]
`composer install` will install only what's already in `composer.lock`.
If you edit `composer.json` yourself instead of using `composer require "sendinblue/api-v3-sdk:*@dev"` you have to use `composer update` after adding a library to composer.json 
E.g. `composer update sendinblue/api-v3-sdk`

Btw: `*@dev` is not a version constraint. You'd better be more specific which version to use see https://getcomposer.org/doc/articles/versions.md
