### ISSUE TITLE
invalid_parameter when add Contact to List

### ISSUE THREAD

**Issue by mikhael87** [sendinblue/APIv3-php-library#47]
When I use the method CreateList I get this error:  [400] Client error: `POST https://api.sendinblue.com/v3/contacts/lists/5/contacts/add` resulted in a `400 Bad Request` response: {"code":"invalid_parameter","message":"Contact already in list and/or does not exist"}

Here is my second parameter, emails:
$emails_data["emails"][] = [
    'email' => 'mihaerusan@gmail.com',
    'emailBlacklisted' => false,
    'smsBlacklisted' => true,
    'updateEnabled' => true,
    'attributes' => [ 'NOMBRE' => 'Ludwig Van Beethoven' ]
];

When one of my paratemers is "NOMBRE", the main key "emails" is request on construct of class AddContactToList.

Please, can someone tell what I'm doing wrong?
Thanks!

**Comment by vishalpawar-tudip** [comment]
Hi @mikhael87,
I tried to create the new contact to a list ID using the API "https://api.sendinblue.com/v3/contacts" and passed the "listIds" => ["1"]  and other attributes in body params.
But, it is not adding into the list specified in the param.
Please let me, if you have any solution for it.
Thanks.

**Comment by mikhael87** [comment]
Hey vishalpawar-tudip,
This issue wasn't a really issue, I confused a that time with some guide, I don't remember it was this in Github, but I tried to add a contact to the incorrect endpoint, invalid_parameter was the key, it doesn't really exists to this endpoint.

Hope it works!

**Comment by alexandra-toder** [comment]
I tried to create the new contact to a list ID using the API "https://api.sendinblue.com/v3/contacts" and passed the "listIds" => [7], but I get the error "[400] Client error: `POST https://api.sendinblue.com/v3/contacts` resulted in a `400 Bad Request` response: {"code":"invalid_parameter","message":"Contact already exist"} " on line 701 of C:\xampp\htdocs\TIZOUTI\tizouti-web\vendor\sendinblue\api-v3-sdk\lib\Api\ContactsApi.php" because the user existing in other list
Please let me know, if you have any solution for it.
Thanks.

**Comment by vivekexpresstech** [comment]
Hello  i am using same add contacts to list but i received error of Invalid list Id please help me to fix this

**Comment by yewyewXD** [comment]
You need to first add the email to your Contact using `https://api.sendinblue.com/v3/contacts`. Then after that you can add the email to a List using `https://api.sendinblue.com/v3/contacts/lists/:listId/contacts/add`
